# set this to true to enable debug mode - not recommended if you're not actually debugging / updating the plugin
debugMode: false

# set this to true if you don't want your players see version of CommandsEX when they type /cex
disableVersion: false

# set this to true if you don't want player commands to be logged in console
# example: [INFO] [Zathrus_Writer] /tploc 0 80 0
logCommands: true

# number of seconds players need to wait between repeating same command again
# this will not stop spamming several different commands (i.e. /home, /sethome, /tell, /me, /home, /sethome...)
# TO BYPASS this (e.g. for your admins), give players (or groups) permission "cex.allowspamcommands"
commandCooldownTime: 4

# database connection details (sqlLite and MySQL currently supported)
#
# host, name, password, port and database and port are REQUIRED ONLY when using MySQL,
# they are ignored for sqlite (except for database, which is used to create a database file itself)
#
# host = host name for the MySQL connection (in most cases can be left as "localhost")
# name = username for the MySQL connection
# password = username for the MySQL connection
# port = connection port for MySQL (in most cases can be left as "3306")
# database = name of your MySQL database to connect to
# prefix = optional, prefix for all CommandsEX tables (e.g. cex_, c_)
#
enableDatabase: true
sqlType: sqlite
database: minecraft
host: localhost
port: 3306
name: root
password: ""
prefix: cex_

# default language to be used for all players until they switch
# this should be a valid ISO Language Code, or Language and Country code
# example: en, en_us, en_gb
defaultLang: en

# list of all languages that will be available to your users,
# should you decide to allow them to change their language on per-user basis
availableLangs: [en, sk]

# chat replacements config file name
chatReplaceFile: playerchat.txt

# player commands replacements config file name
playerCommandsReplaceFile: playercmd.txt

# console commands replacements config file name
consoleCommandsReplaceFile: consolecmd.txt

# how long (in seconds) should a TPA request last before automatic denial
tpaTimeout: 50

# how long (in seconds) should a TPAHERE request last before automatic denial
tpahereTimeout: 50

# time (in seconds) for a player to be on the server before he's allowed to set and use
# their home location using /sethome (or /home set) command
# default: 12 hours (= 43200 seconds)
homeQualifyTime: 43200

# set this to true if you want to allow players to have separate home locations in each world
# setting this to false will set player's home in the world they actually reside when using the /sethome command
allowMultiworldHomes: true

# set this to false if you want everyone on the server see when a player gets kicked
# and the reason why this happened, otherwise set it to true
silentKicks: false

# set this to maximum number of warps each player is allowed to create
# if set to 0, no limit will be imposed - use wisely, it can fill your database quite quickly if you do so
# to allow certain people or groups to create unlimited warp points with this limit set,
# give them cex.warp.bypasslimits permission
maxWarpsPerPlayer: 10

# number of seconds to keep player IPs internally
# this is used when a player repeatedly joins the server, griefs (or spams) heavily and quit right away,
# so we have his IP stored and can ip-ban the guy even after he left
maxIPholdTime: 120

# number of bans for the player to have in history before the system will suggest
# to ban this player permanently
minTempBansWarn: 5

# set this to false if you want everyone on the server see when a player gets banned
# and the reason why this happened, otherwise set it to true
silentBans: false

# these replacement options are not in use yet
replacements:
    default-echo: true
    match-uppercase: true
    commands:
        echo: true
    cutoff:
        length: 1
        indicator: --*

# number of seconds to be silent about join/leave messages and then show them all together
joinSilentTime: 25


# information required to create XMPP (Jabber) connection from your Minecraft server to XMPP server's room
# - xmppEnabled: if true, the XMPP connection will be enabled, otherwise no connection will be made
# - xmppUser: name of the user under which we'll log in to the XMPP (Jabber) service itself
# - xmppHost: the XMPP (Jabber) server, e.g. jabber.com (so when your username is john@jabber.com, user = john, host = jabber.com)
# - xmppPassword: password to use to log the user into the server
# - xmppRoom: name of the room where all chat will happen. This is REQUIRED.
#             You may need to find a service which provides Jabber rooms. I use conf.netlab.cz
#             Therefore my room name is "myroom@conf.netlab.cz" - myroom being the room name, conf.netlab.cz the hostname
# - xmppRoom.password: if the room requires a password to join it, set it up here
# - xmppBotNick: this is the nickname for the plugin. All chat will originate from this nickname.
#                You will, however see who did each chat message originate from.
# - xmppCommandPrefix: when a person from the Jabber room starts line with this character, it will be passed through to the Bukkit server
#                      and executed as if it was an ordinary command from the CONSOLE! Therefore be sure to only add players to xmppAdmins you really trust!
# - xmppAdmins: list of XMPP (Jabber) users who have the right to send commands to Bukkit server. Example = xmppAdmins: [zathrus_writer, johny_cash]
# - xmppEnablePing: if true and nobody sends any message on the server for configurable number of minutes, the bot will simply say (ping) to keep the connection alive
# - xmppEnablePingTime: timeout (in minutes) for the previous setting
# - xmppNotifyChatJoin: if true, players on MC server will see when someone joins Jabber chat, if set to false, they won't
xmppEnabled: false
xmppUser: ""
xmppHost: localhost 
xmppPassword: ""
xmppRoom.name: ""
xmppRoom.password: ""
xmppBotNick: CommandsEX
xmppCommandPrefix: "#"
xmppAdmins: []
xmppEnablePing: true
xmppEnablePingTime: 45
xmppNotifyChatJoin: true

# area around jail location (in blocks) to be still considered a jail, so when people teleport there, they won't be stuck on each other
jailArea: 5

# set true to instantly kill a player who carries TNT block in the inventory and is caught on fire (or damaged from explosion)
# set this to false to leave TNT explosion effect to take over instead and do predefined amount of damage
kamikazeInstaKill: false

# time (in seconds) after which TNT will explode in player's inventory from the moment they catch fire (or are effected by an explosion)
kamikazeTimeout: 3

# time (in seconds) after which the plugins should periodically check how much time players played on the server
# and promote them based on these findings
timedPromoteTaskTime: 180

# configure how much time must a player play on the server before auto-promoted to each group
# syntax...
#   timedpromote:
#       group_name: amount of seconds to play on server to belong here
#
# Example:
#   timedpromote:
#     default: 0
#     rich: 1800
# NOTE: YOU NEED TO ADD THIS CONFIGURATION HERE MANUALLY, NO DEFAULTS ARE CREATED FOR THIS SECTION!

# players in the following groups will be excluded from timed auto-promotions (admins, moderators, ...)
timedPromoteExclude: [admin]

# time (in seconds) after which the plugins should periodically check players' wealth and promote them based on these findings
ecoPromoteTaskTime: 180

# configure how much currency must a player have before auto-promoting him to each group
# syntax...
#   ecopromote:
#       group_name: amount of currency to have to belong here
#
# Example:
#   ecopromote:
#     default: 0
#     rich: 1000
# NOTE: YOU NEED TO ADD THIS CONFIGURATION HERE MANUALLY, NO DEFAULTS ARE CREATED FOR THIS SECTION!

# players in the following groups will be excluded from economy-based auto-promotions (admins, moderators, ...)
ecoPromoteExclude: [admin]

# if this is true, players that drop below treshold of their own group will be removed from this group (i.e. demoted)
ecoPromoteAutoDemote: true

# list of all commands that are used for private messaging, so CommandsEX can intercept them
# IMPORTANT: PLEASE USE LOWERCASE LETTERS FOR THESE COMMANDS OR SPY MODE WILL NOT WORK FOR THEM!
privateMsgCommands: [tell,msg]

# time (in seconds) after which to start a periodic quiz, set to 0 to disable timer
# ... if 0, admins can still force a new quiz by issuing command /quiz start
quizRepeatTime: 500

# time (in seconds) between the quiz is announced and it actually starts (to leave players time to prepare)
quizDelay: 10

# time (in seconds) how long will one quiz question remain valid
quizDuration: 60

# quiz difficulties and rewards - each difficulty has its own rewards set which is cycled through
# one reward will not be repeated twice in a row
# syntax:
#   quizDiff:
#       easy:
#           caseSentisive : 0 (1 for case sensitive, 0 for case insensitive)
#           reward1:
#               2      : 4 (4x grass block)
#               298    : 1 (1x leather helmet)
#			    "35:5" : 8 (8x lime wool block)
# NOTE: YOU NEED TO ADD THIS CONFIGURATION HERE MANUALLY, NO DEFAULTS ARE CREATED FOR THIS SECTION!


# set up your quizzes here (quiz names can be arbitrary)
# syntax...
#   quizzes:
#       quiz_name:
#           question: How long does it take for a baby to be born?
#           difficulty: easy (must be one from quizDiff section above)
#           answers:
#           - 9 months
#           - 9 mnths
#           - 9m
#           - nine months
# NOTE: YOU NEED TO ADD THIS CONFIGURATION HERE MANUALLY, NO DEFAULTS ARE CREATED FOR THIS SECTION!


# Message Of The Day (MOTD) - displayed each time a player joins the server.
# This message will NOT be displayed to NEW players, i.e. those who's never been to your server before. See next config option for that.
#  
# You can set up group-specific messages by using motd_GROUP_NAME like so:
#    motd_kings: "Welcome, my Lord. We are very glad to see you awake again."
#
# You can use the following placeholders in your text:
#     {playername} -> gets replaced by name of the joining player
#     {newline}    -> gets replaced by a new line
#     &0 - &f      -> color codes, values from &0 to &9 and from &a to &f, each one represents a color... see this page for more info: http://v.gd/MCColorCodes
motd: "&aWelcome back, we were hoping to see you again!{newline}&eHave fun and if you need anything, just ask :)"

# Welcome message for all NEW players - i.e. playes who's never been on your server before.
# You can use the following placeholders in your text:
#     {playername} -> gets replaced by name of the joining player
#     {newline}    -> gets replaced by a new line
#     &0 - &f      -> color codes, values from &0 to &9 and from &a to &f, each one represents a color... see this page for more info: http://v.gd/MCColorCodes
motdNewPlayer: "&aWelcome to this wonderful amazing server, &f{playername}!{newline}&ePlease don't grief, spam or curse otherwise feel like home :)"

# time (in seconds) to notify players about a weather change prior to it taking place
weatherNotifyTime: 15

# set this to false if you want to disable upcomming weather notifications for your players
weatherNotifyEnabled: true

# if this is true, a message will be broadcasted each time a player give a kit to another player
kitsBroadcastGifts: true

# set up kits that will be available to your players - kits can be divided into player groups, where * means a group of kits available to everyone
# ... to give a player or group permission to access a kit group (like boneheads below), you need to add a permission of "cex.kits.KIT_GROUP_NAME" to them (e.g. cex.kits.boneheads)
# ... so far, kits cannot be purchased, although this functionality is planned for the future ;)
#
# syntax (first line with the asterisk * is a group of kits available to everyone):
#   "*":
#       starter:
#           onetime: true (if true, this kit can only be obtained by a player once)
#           onjoin : true (if true, new players automatically start with items from this kit in their inventory as they join the server)
#           2      : 4 (4x grass block)
#           298    : 1 (1x leather helmet)
#		    "35:5" : 8 (8x lime wool block)
#   boneheads:
#       supplies:
#           352     : 50 (50x bone)
#           cooldown: 120 (players will not be able to obtain this kit sooner than after this timeout - in seconds)
# NOTE: YOU NEED TO ADD THIS CONFIGURATION HERE MANUALLY, NO DEFAULTS ARE CREATED FOR THIS SECTION!


# default height (in blocks) a player should be ejected into when slapped and no height is provided via parameter
defaultSlapHeight: 20

# set this to true if you want to disable damage to slapped player as they drop down, otherwise set it to false
slapPreventDamage: true

# here you can define into which group to move a player once they die
# ... as you can see in the syntax example, you can use color codes in your commands as well (explained at http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes)
# ... also, you can use $p as a placeholder for name of the player who just died
#
# syntax:
#   knight:
#       toGroup: translucent
#       command: say &eThe time has come for &f$p &eto move on. $p will now be joining ranks of light as a translucent lightkeeper.
# NOTE: YOU NEED TO ADD THIS CONFIGURATION HERE MANUALLY, NO DEFAULTS ARE CREATED FOR THIS SECTION!


# this sets time (in days) after which we delete old records of player groups from database
# ... every time a player dies, his previous group is stored in database, so they can switch back to it via command.
# ... for players that die and do not play on the server anymore, this time is used for cleanup purposes, so the database does not grow too large
# ... set to 0 to disable (not recommended)
deathGroupsCleanupTime: 14

# if this is true, nanosuit will get activated once player equips full chain armor (without helmet) + pumpkin head
# otherwise a full chain armor with its own helmet would mean a nanosuit activation
nanoSuitPumpkin: true

# speed multiplier when nanosuit is activated
# ... this will apply a SPEED potion effect on player where number 0 will apply Speed I, 1 will apply Speed II, 2 will apply Speed III and so on
# CAUTION! Speed potions apply disortion, so with high enough number player's viewpoint can get very narrow!
nanoSuitSpeed: 2

# jump height multiplier when nanosuit is activated
# ... this will apply a JUMP potion effect on player where number 0 will apply Jump I, 1 will apply Jump II, 2 will apply Jump III and so on
nanoSuitJump: 2

# damage multiplier when nanosuit is activated... 2 means double damage (200%), 1.5 means 150% damage and so on
nanoSuitDamage: 2

# how long (in seconds) will the NanoSuit be operational after putting it on
# WARNING: after this time, armor is automatically destroyed and all powers are cancelled
nanoSuitTime: 180

# how long (in seconds) must a player wait before putting on another NanoSuit
nanoSuitRechargeTime: 500

# If the player that is smited with /smite should be told who smited them, set this to true
showMessageOnSmite: false

# If the player that is exploded with /explode should be told who exploded them, set this to true
showMessageOnExplode: false

# INFO COMMAND
# This text will be displayed when player enters /info into chat.
#
# You can use the following placeholders in your text:
#     {playername} -> gets replaced by name of the joining player
#     {newline}    -> gets replaced by a new line
#     &0 - &f      -> color codes, values from &0 to &9 and from &a to &f, each one represents a color... see this page for more info: http://v.gd/MCColorCodes
info: "&aWelcome to this wonderful amazing server, &f{playername}!{newline}&ePlease don't grief, spam or curse otherwise feel like home :)"